server:
  port: 80

baseDir: c:\windows

tempDir: ${baseDir}\temp

datasource:
    driver: com.mysql.jc.jdbc.Driver
    url: jdbc:mysql://localhost/springboot_db
    username: root
    password: wei

